### ISSUE TITLE
Routes

### ISSUE THREAD

**Issue by ssoonmi** [FridaPolished/BookPile#3]
### Backend Routes
- [x] `shelf` should be `shelves`
- [x] GET for `bookshelves` should be `/api/users/:user_id/shelves`
- [x] `book` should be `books`

#### `reviews`
- [x] route for getting all the `reviews` for a single `book`
- [x] route for getting all the `reviews` created by a single `user`
- [x] route for creating/editing/deleting a `review`

#### `read` status
- [x] route for adding/updating a book status

### Frontend Routes
- [x] `/books/:bookId` (make sure to nest ReviewsIndex/ReviewsForm in this component)
- [x] `/books/new` (optional)
- [x] `/books/:bookId/edit` (optional)
- [x] `/users/:userId/shelves`
- [x] `/shelves/:shelfId`
- [x] `/shelves/:shelfId/edit`
- [x] `/shelves/new`

**Comment by FridaPolished** [comment]
Did not include "route for getting all the reviews created by a single user" because it's not a feature in the original site.
